_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  allowed_formats: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_profile: 0
  config_split: 0
  config_update: 0
  content_lock: 0
  content_moderation: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  du_paragraphs: 0
  du_widen: 0
  ducore: 0
  ebrsww: 0
  editor: 0
  editoria11y: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_block: 0
  entity_clone: 0
  entity_embed: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  honeypot: 0
  image: 0
  key: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  node_revision_delete: 0
  options: 0
  pantheon_advanced_page_cache: 0
  pantheon_autopilot_toolbar: 0
  pantheon_secrets: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  redirect: 0
  remote_stream_wrapper: 0
  responsive_image: 0
  role_expire: 0
  simple_sitemap: 0
  simplesamlphp_auth: 0
  simplesamlphp_custom_attributes: 0
  slick: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  url_redirect: 0
  user: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  ds: 1
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
theme:
  pl_drupal: 0
  claro: 0
profile: ducore
