cloneable_entities:
  - config_split
  - path_alias
  - action
  - menu
  - user_role
  - user
  - base_field_override
  - date_format
  - entity_view_display
  - entity_form_mode
  - entity_form_display
  - entity_view_mode
  - environment_indicator
  - block
  - field_storage_config
  - field_config
  - filter_format
  - block_content_type
  - block_content
  - node_type
  - node
  - file
  - editor
  - workflow
  - content_moderation_state
  - taxonomy_term
  - taxonomy_vocabulary
  - image_style
  - media_type
  - media
  - view
  - menu_link_content
  - responsive_image_style
  - paragraphs_type
  - paragraph
  - entity_browser
  - embed_button
  - entity_embed_fake_entity
  - webform
  - webform_options
  - webform_submission
  - key
  - key_config_override
  - simple_sitemap_type
  - simple_sitemap
  - linkit_profile
  - metatag_defaults
  - pathauto_pattern
  - behavior_settings
  - redirect
  - slick
  - url_redirect
