name: Install and DU Core install

on:
  pull_request:
    branches: [ master ]

jobs:
  install_drush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest

      - name: Add Drush to PATH
        run: |
          echo "PATH=$PATH:./vendor/bin" >> $GITHUB_PATH
          echo "PATH=$PATH:./vendor/bin"
          echo "PATH"

      - name: Enable MariaDB 
        uses: shogo82148/actions-setup-mysql@v1
        with:
          distribution: "mariadb"
          mysql-version: "10.4.25"

      - name: Test DU Core Install
        run: |
          drush si ducore -y